# https://github.com/bbatsov/rubocop/blob/master/config/default.yml

Metrics/AbcSize:
  Max: 17

Metrics/LineLength:
  Max: 120

Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
